---
kind: List
apiVersion: v1
items:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: kafka-consumer-app
      labels:
        app: kafka-consumer-app
    spec: {}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: kafka-consumer-app
      name: kafka-consumer-app
    spec:
      replicas: 1
      revisionHistoryLimit: 2
      selector:
        app: kafka-consumer-app
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 3600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: kafka-consumer-app
        spec:
          containers:
            - env:
                - name: KUBERNETES_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
              imagePullPolicy: IfNotPresent
              name: kafka-consumer-app
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 3
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 3
              resources:
                limits:
                  cpu: 500m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              securityContext:
                privileged: false
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /deployments/config
                  name: config
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: kafka-consumer-app
              name: config
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - kafka-consumer-app
            from:
              kind: ImageStreamTag
              name: 'kafka-consumer-app:latest'
          type: ImageChange